<a href="https://colab.research.google.com/github/MohamedKhalidmk/tensor-flow_numpy_fundamentals/blob/main/tensorflowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
scalar=tf.constant(5)
print(f"scalar:{scalar}")
vector=tf.constant([10,10])
print(f"vector:{vector}")
matrix=tf.constant([[10,7],[7,10]])
print(f"matrix:{matrix}")
tf1=tf.random.uniform([5,300],minval=0,maxval=1)
tf2=tf.random.uniform([5,300],minval=0,maxval=1)
print(f"tf:{tf1}")

scalar:5
vector:[10 10]
matrix:[[10  7]
 [ 7 10]]
tf:[[0.71512246 0.6720052  0.12562501 ... 0.2810459  0.08468699 0.7870153 ]
 [0.9885969  0.19633436 0.3549893  ... 0.3456254  0.6047075  0.5624163 ]
 [0.5932139  0.50727713 0.9665445  ... 0.3950467  0.27792752 0.04143667]
 [0.05235839 0.6991217  0.42149186 ... 0.16872334 0.01092172 0.1391319 ]
 [0.10274029 0.4784789  0.54626167 ... 0.74624896 0.73664796 0.11685467]]


In [ ]:
print(f"scalar shape:{scalar.shape}")
print(f"scalar rank:{tf.rank(scalar)}")
print(f"scalar size:{tf.size(scalar)}\n")

print(f"vector shape:{vector.shape}")
print(f"vector rank:{tf.rank(vector)}")
print(f"vector size:{tf.size(vector)}\n")

print(f"matrix shape:{matrix.shape}")
print(f"matrix rank:{tf.rank(matrix)}")
print(f"matrix size:{tf.size(matrix)}\n")

print(f"tf shape:{tf1.shape}")
print(f"tf rank:{tf.rank(tf1)}")
print(f"tf size:{tf.size(tf1)}\n")

print(f"tf shape:{tf.shape(tf2)}")
print(f"tf rank:{tf.rank(tf2)}")
print(f"tf size:{tf.size(tf2)}\n")

scalar shape:()
scalar rank:0
scalar size:1

vector shape:(2,)
vector rank:1
vector size:2

matrix shape:(2, 2)
matrix rank:2
matrix size:4

tf shape:(5, 300)
tf rank:2
tf size:1500

tf shape:[  5 300]
tf rank:2
tf size:1500



In [ ]:
tf_mal=tf.matmul(tf1,tf2,transpose_b=True)
print(f"tf_mal:{tf_mal}\n")
tf_dot = tf.reduce_sum(tf1*tf2)
print(f"tf_dot:{tf_dot}\n")
tf_dot2=tf.tensordot(tf1,tf2,axes=[[1],[1]])#different way each row of tf1 with each row of tf2
print(f"tf_dot2:{tf_dot2}\n")

tf_mal:[[77.84088  72.07089  75.88426  78.49739  81.80726 ]
 [76.37148  73.53203  75.12153  74.802895 76.78448 ]
 [75.260666 68.32137  72.49104  70.38301  73.65723 ]
 [69.6679   66.860435 69.54571  72.057495 70.950226]
 [79.28924  72.57329  77.246    74.42705  80.147934]]

tf_dot:376.0693664550781

tf_dot2:[[77.84088  72.07089  75.88426  78.49739  81.80726 ]
 [76.37148  73.53203  75.12153  74.802895 76.78448 ]
 [75.260666 68.32137  72.49104  70.38301  73.65723 ]
 [69.6679   66.860435 69.54571  72.057495 70.950226]
 [79.28924  72.57329  77.246    74.42705  80.147934]]



In [ ]:
tf3=tf.random.uniform([224,224,3],minval=0,maxval=1)
tf_max_axis1=tf.reduce_max(tf3,axis=0)#along first axis
tf_min_axis1=tf.reduce_min(tf3,axis=0)
tf_max=tf.reduce_max(tf_max)
tf_min=tf.reduce_min(tf_min)
print(f"tf_max:{tf_max}")
print(f"tf_min:{tf_min}\n")
print(f"tf_max_axis1:{tf_max_axis1}")
print(f"tf_min_axis1:{tf_min_axis1}\n")

tf_max:0.9999992847442627
tf_min:4.649162292480469e-06

tf_max_axis1:[[0.99770033 0.9827558  0.995453  ]
 [0.9880744  0.99331117 0.9968724 ]
 [0.9933852  0.99634945 0.99590325]
 [0.9959837  0.99913704 0.9919869 ]
 [0.98989344 0.9986234  0.9573358 ]
 [0.9975617  0.99850595 0.9985882 ]
 [0.9959241  0.99597454 0.9951112 ]
 [0.9947567  0.99970925 0.99213934]
 [0.9972235  0.9892894  0.9839047 ]
 [0.9989809  0.99449253 0.99862146]
 [0.998065   0.998302   0.9954747 ]
 [0.998212   0.99645376 0.9996673 ]
 [0.9934529  0.9979671  0.9957826 ]
 [0.9945018  0.9939985  0.99350524]
 [0.99764097 0.99893355 0.999241  ]
 [0.98684466 0.9963162  0.980656  ]
 [0.9996786  0.9954169  0.996503  ]
 [0.99873734 0.99585164 0.9984498 ]
 [0.9996587  0.9985757  0.9926157 ]
 [0.9879335  0.9967803  0.994995  ]
 [0.99360144 0.9977778  0.9931067 ]
 [0.99661446 0.98429275 0.9962431 ]
 [0.9985504  0.9868982  0.9970242 ]
 [0.99826944 0.9953853  0.99360144]
 [0.9964819  0.9952822  0.9991077 ]
 [0.99164295 0.9993949  0.99794

In [ ]:
tf4=tf.random.uniform([1,224,224,3],minval=0,maxval=1)
tf_squeezed=tf.squeeze(tf4)
print(f"tf_squeezed:{tf_squeezed.shape}")

tf_squeezed:(224, 224, 3)


In [ ]:
tf5=tf.range(1,11)
print(f"tf5:{tf5}")
tf5_max_index=tf.argmax(tf5)
print(f"tf5 max index:{tf5_max_index}")
tf_one_hot=tf.one_hot(tf5,depth=9)
print(f"tf_one_hot:{tf_one_hot}")

tf5:[ 1  2  3  4  5  6  7  8  9 10]
tf5 max index:9
tf_one_hot:[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
